env = ENV.to_hash
VAGRANTFILE_API_VERSION = '2'

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  # trusty (latest), virtualbox only
  config.vm.box = 'ubuntu/trusty64'

  config.vm.provider(:virtualbox) do |v|
    v.name = 'bosh-docker-builder'
    v.customize ['modifyvm', :id, '--cpus', '4']
    v.customize ['modifyvm', :id, '--memory', '4096']
  end

  # mount bosh dir for testing
  config.vm.synced_folder('../../', '/opt/bosh', owner: 'root', group: 'root')

  if Vagrant.has_plugin?("vagrant-proxyconf")
    config.proxy.http     = env.fetch('http_proxy')
    config.proxy.https    = env.fetch('https_proxy')
    config.proxy.no_proxy = env.fetch('no_proxy')

    config.vm.provision "shell",
      inline: "echo 'export http_proxy=\"#{env["http_proxy"]}\"' >> /etc/default/docker"
  end

  config.vm.provision 'docker',
    images: ['bosh/integration']
end
